spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jdbc?serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      stat-view-servlet: #配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter: #监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      #多个filter 配法
      filters: stat,wall #底层开启功能，stat(sql监控)，wall（防火墙）

      # Spring监控配置
      aop-patterns: com.yws.* #监控SpringBean

      # 单个filter 配法
      filter:
        stat: #对上面filters里的stat的详细配置
          slow-sql-millis: 1000 #慢查询的时间
          logSlowSql: true #是否记录慢查询
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false





  #    自定义druid
#    filters: stat,wall
#    max-active: 10

  jdbc:
    template:
      query-timeout: 3
  redis:
    host: 192.168.214.128
    port: 6379
    client-type: jedis
    jedis:
      pool:
        max-active: 10
        max-idle: 5

#    client-type: lettuce
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 5



#  mvc:
#    servlet:
#      path: /mvc/

#配置mybatis规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml #sql映射文件位置

  configuration:
    map-underscore-to-camel-case: true





