spring:
  mvc:
    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true

    contentnegotiation:
      favor-parameter: true

  web:
    resources:
      static-locations: [classpath:/myStatic/]
