spring:
  mvc:
    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true

    contentnegotiation:
      favor-parameter: true
      #media-types: {yws: application/x-yws}

  web:
    resources:
      static-locations: [classpath:/myStatic/]
